name: Lint

on:
  push:
  pull_request:
    branches:
      - development
      - main

jobs:
  formatting:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python -m pip install --upgrade ruff
      - run: ruff check . --diff
      - run: ruff format . --diff
